import { ContactMethod, LeadSource, LeadStatus } from '@/shared/types/enums';

export const defaultLeadRequest = {
  businessName: '',
  contactName: '',
  contactEmail: '',
  phoneNumber: '',
  streetNumber: '',
  streetName: '',
  aptUnitBldg: '',
  postalCode: '',
  cityId: null,
  stateId: null,
  countryId: null,
  source: LeadSource.GOVERNMENT,
  sourceUrl: '',
  uploadedFile: '',
  status: LeadStatus.PENDING,
  notes: '',
  vendorId: null,
};

export const defaultLeadResponse = {
  id: null,
  businessName: '',
  phoneNumber: '',
  streetNumber: '',
  streetName: '',
  aptUnitBldg: '',
  postalCode: '',
  city: '',
  province: '',
  country: '',
  formattedAddress: '',
  source: LeadSource.GOVERNMENT,
  sourceUrl: '',
  uploadedFile: '',
  previewUrl: '',
  status: LeadStatus.PENDING,
  notes: '',
  vendorId: null,
  vendorUniqueId: '',
  createdAt: '',
  updatedAt: '',
  addedBy: null,
  addedByName: '',
  lastModifiedBy: null,
  lastModifiedByName: '',
  validatedBy: null,
  validatedByFirstName: '',
  validatedByLastName: '',
  validatedAt: '',
  contactMethod: null,
  contactMethodDetails: '',
  extensionNumber: '',
  contactName: '',
  contactEmail: '',
  position: '',
  addedByManager: false,
  assignedTo: null,
  assignedToFirstName: '',
  assignedToLastName: '',
  assignedAt: null,
};

export const defaultLeadValidationRequest = {
  status: LeadStatus.PENDING,
  notes: '',
};

export const defaultInitiateContactRequest = {
  contactMethod: ContactMethod.PHONE,
  contactMethodDetails: '',
  extensionNumber: '',
  contactName: '',
  position: '',
};
